# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 670da877f78dc17dd947a0feb9411a20ebec9c96b1cae1a306462abfc91bffff3ea7b2438f5a66e7e72118f1aac3ba9bd8162a4838adf79074f5ed7dd65d4391

test:
  secret_key_base: 442099253e085fb4e2c4b11b3217c6c102067759ff28d859b276ee7131844fd44f0c1fbd13923ae91f384b00c1a162ad05d1cc5beecf921793c2f12a0a80312c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
